/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SosRouteImport } from './routes/sos'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as GuardianRouteImport } from './routes/guardian'
import { Route as CircleRouteImport } from './routes/circle'
import { Route as IndexRouteImport } from './routes/index'

const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianRoute = GuardianRouteImport.update({
  id: '/guardian',
  path: '/guardian',
  getParentRoute: () => rootRouteImport,
} as any)
const CircleRoute = CircleRouteImport.update({
  id: '/circle',
  path: '/circle',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/circle': typeof CircleRoute
  '/guardian': typeof GuardianRoute
  '/heatmap': typeof HeatmapRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/sos': typeof SosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/circle': typeof CircleRoute
  '/guardian': typeof GuardianRoute
  '/heatmap': typeof HeatmapRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/sos': typeof SosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/circle': typeof CircleRoute
  '/guardian': typeof GuardianRoute
  '/heatmap': typeof HeatmapRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/sos': typeof SosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/circle'
    | '/guardian'
    | '/heatmap'
    | '/login'
    | '/profile'
    | '/signup'
    | '/sos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/circle'
    | '/guardian'
    | '/heatmap'
    | '/login'
    | '/profile'
    | '/signup'
    | '/sos'
  id:
    | '__root__'
    | '/'
    | '/circle'
    | '/guardian'
    | '/heatmap'
    | '/login'
    | '/profile'
    | '/signup'
    | '/sos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CircleRoute: typeof CircleRoute
  GuardianRoute: typeof GuardianRoute
  HeatmapRoute: typeof HeatmapRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  SosRoute: typeof SosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian': {
      id: '/guardian'
      path: '/guardian'
      fullPath: '/guardian'
      preLoaderRoute: typeof GuardianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle': {
      id: '/circle'
      path: '/circle'
      fullPath: '/circle'
      preLoaderRoute: typeof CircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CircleRoute: CircleRoute,
  GuardianRoute: GuardianRoute,
  HeatmapRoute: HeatmapRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  SosRoute: SosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
